name: CICD Nokia

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t nirajdkr1/nokia .
      - name: Publish image to docker hub
        run: docker push nirajdkr1/nokia:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull nirajdkr1/nokia:latest
      - name: Delete old container
        run: docker rm -f nokia-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name nokia-container nirajdkr1/nokia

